### ISSUE TITLE
数据视图组件数字属性的进度条样式, 增加一个--progress-value的style属性

### ISSUE THREAD

**Issue by RavenHogWarts** [vran-dev/obsidian-components-release#1]
`<div class="components--progress-bar-value" data-value="25" data-max="100" style="width: 25%; "></div>`

这是目前的进度条, 在修改样式时, 如需添加一个after伪元素跟随进度条一起移动
以data-max="100"为例, 需要手动添加data-value从0到100的每一个样式, 而且如果data-max为其他值, 样式还需要做其他修改

期望插件能够先将进度处理成百分比的值, 计算Math.floor((data-value/data-max)*100)并放在--progress-value中, 比如:
`<div class="components--progress-bar-value" data-value="25" data-max="100" style="width: 25%; --progress-value: 25"></div>`

如此便能在css中通过动态的方式设置after伪元素的位置
```css
.components--progress-bar-value[data-value]::after {
    right: calc(100% - var(--progress-value));
}
```

佬考虑一下, 现在的css光0到100的样式就得写100行
